const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('toast-show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('toast-show'),2800)}
async function api(url,opt={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{...opt,signal:controller.signal});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}catch(e){if(e.name==='AbortError')throw Error('The request timed out. The Command Center remains available; you can retry this panel.');throw e}finally{clearTimeout(timeout)}}
let me=null,studentPaid=false,activeMeeting=null,meetingTimer=null,signalTimer=null,participantTimer=null,messageTimer=null,lastSignal=0,peers=new Map(),candidateQueues=new Map(),remoteUsers=new Map();
function showSection(name){
  const target=name==='overview'?'overviewSection':name+'Section';
  const panel=document.getElementById(target);
  if(!panel){toast('This Command Center section is unavailable.');return}
  document.querySelectorAll('main section').forEach(s=>s.classList.toggle('hidden',s.id!==target));
  document.querySelectorAll('aside a').forEach(a=>a.classList.toggle('active',a.dataset.section===name));
  panel.classList.remove('fx-section-enter');void panel.offsetWidth;panel.classList.add('fx-section-enter');
  if(name==='admin'){ if(me?.role==='admin')loadAdmin(); else toast('Administrator access is required.'); }
  if(name==='messages'){loadContacts();loadMessages()}
  if(name==='resources')loadResources();
  if(name==='gradebook'&&(me?.role==='teacher'||me?.role==='admin'))loadGradebook();
  if(name==='meetings')loadMeetings();
  if(name==='settings')fillProfile();
}
async function init(){try{const auth=await api('/api/auth/me');me=auth.user;if(!me||!me.id)throw Error('Your session is no longer valid.');$('userName').textContent=me.name||me.username||'User';$('roleBadge').textContent=me.role||'user';$('welcome').textContent=`Welcome, ${(me.name||me.username||'User').split(' ')[0]}`;$('roleText').textContent=me.role==='admin'?'You have full administration access across the Kersa digital campus.':`You are signed in as ${me.role}.`;if(me.role!=='admin'){document.querySelectorAll('[data-section="admin"],#adminQuick').forEach(x=>x.classList.add('hidden'))}if(me.role==='teacher'||me.role==='admin'){$('gradeForm').classList.remove('hidden');$('resourceForm').classList.remove('hidden');$('meetingForm').classList.remove('hidden')}document.body.classList.add('loaded-page');const jobs=[['overview',loadOverview],['notifications',loadNotifications],['contacts',loadContacts],['meetings',loadMeetings],['profile',fillProfile]];for(const [name,fn] of jobs){try{await fn()}catch(e){console.warn(`Kersa ${name} panel failed:`,e);toast(`${name} panel could not load. Other controls remain available.`)}}if(me.role==='admin'){showSection('admin');await loadAdmin()}}catch(e){console.error('Kersa Command Center authentication failed:',e);document.body.classList.add('loaded-page');setTimeout(()=>{location.href='/login.html'},500)}}
async function loadNotifications(){try{const rows=await api('/api/notifications');const box=$('notificationPanel');if(!box)return;box.innerHTML=`<div class="section-title"><h2>🔔 Automatic system responses</h2><span class="muted">Private notifications for your account</span></div>${rows.length?rows.slice(0,8).map(x=>`<div class="admin-message"><b>${esc(x.title)}</b><p>${esc(x.body)}</p><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join(''):'<div class="empty-state">No new system responses.</div>'}`;}catch(e){}}
function renderClassroom(profile,timetable){const section=$('classroomSection'), link=$('classroomLink'); if(!section)return; const approved=profile?.status==='approved'; link?.classList.toggle('hidden',!approved); if(!approved){section.classList.add('hidden');return;} $('classStatus').textContent='ACTIVE CLASS'; $('classroomContent').innerHTML=`<div class="classroom-grid"><div class="class-card"><span>CLASS</span><strong>Grade ${esc(profile.grade)}</strong><small>${esc(profile.stream||'General')}</small></div><div class="class-card"><span>STUDENT</span><strong>${esc(profile.name)}</strong><small>${esc(profile.username||'')}</small></div><div class="class-card"><span>STATUS</span><strong>Approved</strong><small>Your class space is ready.</small></div></div><h3>Class timetable</h3><div class="table-list">${(timetable||[]).map(x=>`<div class="table-row"><b>${esc(x.day_name)}</b><span>${esc(x.period)}</span><span>${esc(x.subject)}</span><span>${esc(x.teacher||'—')}</span></div>`).join('')||'<div class="empty-state">Your class timetable will appear here when published.</div>'}</div>`;}
async function loadOverview(){const d=await api('/api/dashboard');let widgets=[];if(d.role==='admin'){widgets=[['👥',d.stats.users,'Users'],['🎓',d.stats.students,'Students'],['📰',d.stats.announcements,'Announcements'],['📚',d.stats.resources,'Resources'],['🖼️',d.stats.gallery,'Gallery'],['⏳',d.stats.pending,'Pending registrations']];$('registrationStatus').innerHTML='<div class="admin-callout"><b>Registration control center</b><span>Approve, reject, reply and print every application from Administration → Registrations.</span></div>'}else if(d.role==='student'){widgets=[['📈',`${d.profile?.average||0}%`,'Average'],['🟢',`${d.profile?.attendance||0}%`,'Attendance'],['📝',d.profile?.pending_assignments||0,'Assignments'],['🎓',`Grade ${d.profile?.grade||'—'}`,'Current grade']];renderGrades(d.grades||[]);renderRows(d.timetable||[]);renderClassroom(d.profile,d.timetable);$('registrationStatus').innerHTML=`<div class="registration-banner status-${esc(d.profile?.status||'pending')}"><div><small>REGISTRATION STATUS</small><h3>${esc(String(d.profile?.status||'pending').toUpperCase())}</h3><p>${esc(d.profile?.admin_reply||'Your application is being reviewed. You will see the administrator response here.')}</p></div></div>`}else if(d.role==='parent'){renderClassroom(null,[]);widgets=[['👨‍👩‍👧',d.children?.length||0,'Connected children']];renderChildren(d.children||[]);$('registrationStatus').innerHTML=''}else{renderClassroom(null,[]);widgets=[['📚',d.resources?.length||0,'Your resources'],['📝',d.assignments?.length||0,'Assignments']];renderRows([]);$('registrationStatus').innerHTML=''}$('widgets').innerHTML=widgets.map(x=>`<div class="widget"><b>${esc(x[0])} ${esc(x[1])}</b><span>${esc(x[2])}</span></div>`).join('');if(d.role==='admin')$('timetable').innerHTML='<div class="table-row"><b>Administration</b><span>Full control</span><span>Registrations</span><span>Content • Media • Users • Meetings</span></div>'}
function renderRows(rows){$('timetable').innerHTML=rows.length?rows.map(x=>`<div class="table-row"><b>${esc(x.day_name||x.name)}</b><span>${esc(x.period||'')}</span><span>${esc(x.subject||x.stream||'')}</span><span>${esc(x.teacher||'')}</span></div>`).join(''):'<div class="empty-state">No timetable records yet.</div>'}
function renderGrades(rows){$('gradebook').innerHTML=rows.length?`<div class="mini-table"><div class="table-row"><b>Subject</b><span>Score</span><span>Term</span></div>${rows.map(x=>`<div class="table-row"><b>${esc(x.subject)}</b><span>${esc(x.score)}</span><span>${esc(x.term)}</span></div>`).join('')}</div>`:'<div class="empty-state">No grades published yet.</div>'}
function renderChildren(rows){$('timetable').innerHTML=rows.length?rows.map(x=>`<div class="table-row"><b>${esc(x.name)}</b><span>Grade ${esc(x.grade)}</span><span>${esc(x.stream||'')}</span><span>${esc(x.status)}</span></div>`).join(''):'<div class="empty-state">No students are linked to this account.</div>'}
async function loadContacts(){if(!$('contactSelect'))return;try{const rows=await api('/api/contacts');$('contactSelect').innerHTML='<option value="">Select a teacher, administrator or school contact</option>'+rows.map(x=>`<option value="${x.id}">${esc(x.name)} — ${esc(x.role)}</option>`).join('')}catch(e){toast(e.message)}}
async function loadMessages(){try{const rows=await api('/api/messages');$('messageList').innerHTML=rows.length?rows.map(x=>`<div class="chat-message ${x.sender_id===me.id?'mine':''}"><b>${esc(x.sender_name)}</b>${x.subject?`<small class="message-subject">${esc(x.subject)}</small>`:''}<p>${esc(x.body)}</p><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join(''):'<div class="empty-state">No messages yet.</div>';$('messageList').scrollTop=$('messageList').scrollHeight}catch(e){toast(e.message)}}
async function sendMessage(){const receiverId=Number($('contactSelect').value),subject=$('messageSubject').value.trim(),body=$('messageBody').value.trim();if(!receiverId||!body)return toast('Choose a contact and write a message.');try{await api('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receiverId,subject,body})});$('messageBody').value='';$('messageSubject').value='';await loadMessages();toast('Message sent.')}catch(e){toast(e.message)}}
async function loadResources(){try{const rows=await api('/api/resources');$('resourceList').innerHTML=rows.map(x=>`<div class="resource-card"><div><b>${esc(x.title)}</b><span>${esc(x.subject||'General')} • Grade ${esc(x.grade||'All')}</span></div><a class="btn btn-small" href="${x.file_url}" target="_blank" rel="noopener">Open</a>${me.role==='admin'?`<button class="btn btn-small resource-delete-btn" data-id="${x.id}">Delete</button>`:''}</div>`).join('')||'<div class="empty-state">No resources available.</div>'}catch(e){toast(e.message)}}
async function loadGradebook(){try{const rows=await api('/api/teacher/gradebook');$('gradebook').innerHTML=rows.length?`<div class="admin-table-wrap"><table class="data-table"><thead><tr><th>Student</th><th>Grade</th><th>Subject</th><th>Score</th><th>Term</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.student_name)}</td><td>${esc(x.grade)}</td><td>${esc(x.subject||'—')}</td><td>${esc(x.score??'—')}</td><td>${esc(x.term||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No gradebook records yet.</div>';$('gradebookHint').textContent=me.role==='admin'?'Administrator inspection and control':'Teacher grade entry';}catch(e){toast(e.message)}}
async 
async 
async 
async function loadAdmin(){try{const s=await api('/api/admin/summary');$('adminWidgets').innerHTML=Object.entries(s).map(([k,v])=>`<div class="widget"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('');const tasks=[loadStudents,loadUsers,loadGradebook,loadAnnouncements,loadEvents,loadGallery,loadContactsAdmin,loadMeetingsAdmin,loadParentLinks,loadAcknowledgmentMedia];const results=await Promise.allSettled(tasks.map(fn=>fn()));const failed=results.filter(x=>x.status==='rejected');await populateAdminGradeStudents();fillAdminProfile();if(failed.length)toast(`${failed.length} admin panel request(s) need attention; the dashboard is still available.`)}catch(e){toast(e.message)}}
async function populateAdminGradeStudents(){if(!$('adminGradeStudent'))return;const students=studentCache.filter(x=>x.status==='approved');$('adminGradeStudent').innerHTML='<option value="">Select approved student</option>'+students.map(x=>`<option value="${x.id}">${esc(x.name)} — Grade ${esc(x.grade)}${x.stream?` — ${esc(x.stream)}`:''}</option>`).join('')}
async function postAdminGrade(){const form=$('adminGradeForm');if(!form)return;try{await api('/api/teacher/grades',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await loadGradebook();toast('Grade posted / updated successfully.')}catch(e){toast(e.message)}}
let studentCache=[];
async function loadStudents(){studentCache=await api('/api/admin/students');renderStudentTable();await populateAdminGradeStudents()}
function renderStudentTable(){const q=$('studentSearch')?.value.toLowerCase()||'',status=$('studentStatusFilter')?.value||'';const rows=studentCache.filter(x=>(!status||x.status===status)&&(!q||[x.name,x.email,x.phone,x.fan_number,x.region,x.woreda,x.town_city].join(' ').toLowerCase().includes(q)));$('studentTable').innerHTML=rows.length?`<table class="data-table registration-table"><thead><tr><th>Student</th><th>Contact</th><th>Location</th><th>Academic</th><th>Status</th><th>Admin reply</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>FAN: ${esc(x.fan_number)}</small><br><small>User: ${esc(x.username)}</small></td><td>${esc(x.email)}<br>${esc(x.phone||'')}<br><small>Family: ${esc(x.family_phone||'—')}</small><br><small>Family FAN: ${esc(x.family_fan_number||'—')}</small></td><td>${esc(x.region)}<br>${esc(x.woreda)}, ${esc(x.town_city)}</td><td>Grade ${esc(x.grade)}<br>${esc(x.stream||'')}</td><td><select class="student-status-select" data-id="${x.id}"><option ${x.status==='pending'?'selected':''}>pending</option><option ${x.status==='approved'?'selected':''}>approved</option><option ${x.status==='rejected'?'selected':''}>rejected</option></select></td><td><textarea class="student-reply" data-id="${x.id}" placeholder="Reply to student…">${esc(x.admin_reply||'')}</textarea></td><td><div class="action-stack"><button class="btn btn-small btn-primary approve-student-btn" data-id="${x.id}">✓ Approve</button><button class="btn btn-small reject-student-btn" data-id="${x.id}">✕ Reject</button><button class="btn btn-small save-student-btn" data-id="${x.id}">Save reply</button><button class="btn btn-small print-student-btn" data-id="${x.id}">Print / PDF</button>${x.grade8_report_card?`<a class="btn btn-small" target="_blank" rel="noopener" href="/api/admin/students/${x.id}/report-card">Report card</a>`:''}</div></td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">No matching registrations.</div>'}
async function updateStudent(id,status,reply){const body={status};if(reply!==undefined)body.adminReply=reply;const result=await api('/api/admin/students/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadStudents();await loadOverview();if(result.credentials){alert(`STUDENT APPROVED\n\nUnique username: ${result.credentials.username}\nUnique password: ${result.credentials.password}\n\nThe student can also retrieve these credentials from the registration-status checker.`);}toast(`Registration ${status}.`)}
async function loadUsers(){const rows=await api('/api/admin/users');$('userTable').innerHTML=`<div class="admin-table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Email</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.username||'—')}</td><td>${esc(x.role)}</td><td>${esc(x.email)}</td><td>${x.id!==me.id?`<button class="btn btn-small user-delete-btn" data-id="${x.id}">Delete</button>`:'<span class="muted">Current admin</span>'}</td></tr>`).join('')}</tbody></table></div>`}
async function loadAnnouncements(){const rows=await api('/api/announcements');$('adminAnnouncements').innerHTML=rows.map(x=>`<div class="admin-message"><b>${esc(x.title)}</b><p>${esc(x.body)}</p><button class="btn btn-small announcement-delete-btn" data-id="${x.id}">Delete</button></div>`).join('')}
async function loadEvents(){const rows=await api('/api/admin/events');$('adminEvents').innerHTML=rows.map(x=>`<div class="admin-message"><b>${esc(x.title)}</b><span>${esc(x.event_date)}</span><p>${esc(x.description||'')}</p><button class="btn btn-small event-delete-btn" data-id="${x.id}">Delete</button></div>`).join('')}
async function loadAcknowledgmentMedia(){try{const rows=await api('/api/acknowledgment-media');const map=new Map(rows.map(x=>[x.slot,x]));document.querySelectorAll('.ack-upload-form').forEach(form=>{const found=map.get(form.dataset.ackSlot),status=form.querySelector('.ack-upload-status'),input=form.querySelector('input[type=file]'),button=form.querySelector('button');if(found){status.innerHTML=`<div class="ack-locked"><img src="${esc(found.image_url)}" alt="${esc(found.title)}"><strong>🔒 Permanently locked</strong><small>Uploaded ${esc(new Date(found.uploaded_at).toLocaleString())}. No replacement or deletion is available.</small></div>`;input.disabled=true;button.disabled=true;button.textContent='Image permanently locked';form.classList.add('ack-locked-form')}else{status.textContent='Not uploaded yet — this slot can be used once.';input.disabled=false;button.disabled=false;button.textContent='Upload once & lock';form.classList.remove('ack-locked-form')}});$('ackAdminList').innerHTML=rows.length?rows.map(x=>`<figure class="gallery-item"><img src="${esc(x.image_url)}" alt="${esc(x.title)}"><figcaption>🔒 ${esc(x.title)} — permanently locked</figcaption></figure>`).join(''):'<div class="empty-state">No acknowledgment images have been uploaded yet.</div>'}catch(e){console.warn(e)}}
async function loadGallery(){const rows=await api('/api/gallery');$('adminGallery').innerHTML=rows.map(x=>`<figure class="gallery-item"><img src="${x.image_url}" alt="${esc(x.title)}"><figcaption>${esc(x.title)} <button class="btn btn-small gallery-delete-btn" data-id="${x.id}">Delete</button></figcaption></figure>`).join('')}
async function loadContactsAdmin(){const rows=await api('/api/admin/contacts');$('contactInbox').innerHTML=rows.map(x=>`<div class="admin-message"><b>${esc(x.name)} — ${esc(x.subject)}</b><p>${esc(x.message)}</p><small>${esc(x.email)} ${esc(x.phone||'')}</small><select class="contact-status-select" data-id="${x.id}"><option ${x.status==='new'?'selected':''}>new</option><option ${x.status==='read'?'selected':''}>read</option><option ${x.status==='resolved'?'selected':''}>resolved</option></select></div>`).join('')||'<div class="empty-state">No contact messages.</div>'}
async function loadMeetingsAdmin(){const rows=await api('/api/meetings');$('adminMeetings').innerHTML=rows.map(x=>`<div class="admin-message"><b>${esc(x.title)}</b><span>${esc(x.room_code)} • ${esc(x.mode)}</span><button class="btn btn-small meeting-delete" data-id="${x.id}">Delete</button></div>`).join('')}
async function loadParentLinks(){try{const users=await api('/api/admin/users');const students=studentCache;const parents=users.filter(x=>x.role==='parent');$('parentSelect').innerHTML=parents.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('studentSelect').innerHTML=students.map(x=>`<option value="${x.id}">${esc(x.name)} — Grade ${esc(x.grade)}</option>`).join('');}catch(e){}}
async function loadMeetings(){const rows=await api('/api/meetings');$('meetingList').innerHTML=rows.map(x=>`<div class="meeting-card"><div><b>${esc(x.title)}</b><span>${esc(x.creator_name||'Kersa')} • ${esc(x.mode||'hybrid')} • ${esc(x.room_code)}</span></div><button class="btn btn-primary" data-meeting="${x.id}">Join</button></div>`).join('')||'<div class="empty-state">No meetings available.</div>'}
async function joinMeeting(id){if(activeMeeting)await leaveMeeting();try{await api(`/api/meetings/${id}/join`,{method:'POST'});const rows=await api('/api/meetings');activeMeeting=rows.find(x=>x.id===id);if(!activeMeeting)throw Error('Meeting not found.');$('meetingRoom').classList.remove('hidden');$('meetingTitle').textContent=activeMeeting.title;$('meetingMode').textContent='LIVE VIDEO + TEXT';showSection('meetings');try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$('localVideo').srcObject=stream;toast('Camera and microphone connected.')}catch(e){toast('Camera/microphone unavailable. Text mode remains active.')}lastSignal=0;await refreshParticipants();meetingTimer=setInterval(loadMeetingChat,1200);signalTimer=setInterval(pollSignals,900);participantTimer=setInterval(refreshParticipants,3000);await loadMeetingChat();await refreshParticipants();}catch(e){toast(e.message)}}
async function refreshParticipants(){i
